dwaii/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from medicine.views import index, adminDash, privacy, contact, aboutUs
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('adminDwaiiDashboard/', admin.site.urls),
    path('', index, name='index'),
    path('aboutus/', aboutUs, name='aboutUs'),
    path('adminDashboard', adminDash, name='adminDash'),
    path('medicine/', include('medicine.urls')),
    path('', include('pwa.urls')),
    path('privacy/', privacy, name='privacy'),
    path('contact/', contact, name='contact'),
    path("ads.txt",RedirectView.as_view(url=staticfiles_storage.url("ads.txt")),),

    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

med/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView
from medicine.views import index, adminDash, privacy, contact, aboutUs
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken import views

urlpatterns = [
                  path('adminDwaiiDashboard/', admin.site.urls),
                  path('', index, name='index'),
                  path('aboutus/', aboutUs, name='aboutUs'),
                  path('adminDashboard', adminDash, name='adminDash'),
                  path('medicine/', include('medicine.urls')),
                  path('', include('pwa.urls')),
                  path('privacy/', privacy, name='privacy'),
                  path('contact/', contact, name='contact'),
                  path("ads.txt", RedirectView.as_view(url=staticfiles_storage.url("ads.txt")), ),
                  path('api-token-auth/', views.obtain_auth_token, name='api-token-auth'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicine/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from medicine.views import search, allMedicine, sign, logout_backend, \
    profile, add_to_storage, productinfo, Registerinfo, editproduct, \
    editproductBackend, addMedicine, requestMedicine, requestList, visitorProfile, requestinfo, addBranch, \
    searchRequest, searchdonate, donateList, Editinfo, edit_medicine, signup, medicineList, medicineDetail, storageList, \
    pharmacyList, MedicineListView, UserRecordView
from django.contrib.auth import views as auth_views

urlpatterns = [
                  path('search', search, name='search'),
                  path('searchRequest', searchRequest, name='searchRequest'),
                  path('searchDonate', searchdonate, name='searchDonate'),
                  path('sign/', sign, name='sign'),
                  path('signup/', signup, name='signup'),
                  path('', allMedicine, name='allMedicine'),
                  path('requestList/', requestList, name='requestList'),
                  path('donateList/', donateList, name='donateList'),
                  path('request/add', requestMedicine, name='requestMedicine'),
                  path('profile/add_to_storage/', add_to_storage, name='add_to_storage'),
                  path('profile/addMedicine/', addMedicine, name='addMedicine'),
                  path('profile/medicine/<int:medId>', edit_medicine, name='edit_medicine'),
                  path('profile/', profile, name='profile'),
                  path('profile/<int:phUrl>', visitorProfile, name='visitProfile'),
                  path('logout/', logout_backend, name='logout'),
                  path('info/<int:productId>', productinfo, name='productinfo'),
                  path('request/info/<int:requestId>', requestinfo, name='requestinfo'),
                  path('info/edit/<int:productId>', editproduct, name='editproduct'),
                  path('info/editBackend/<int:productId>', editproductBackend, name='editproductBackend'),
                  path('profile/inforegister', Registerinfo, name='infoRegister'),
                  path('profile/addBranch', addBranch, name='addBranch'),
                  path('profile/edit_information', Editinfo, name='edit_information'),

                  # API VIEWS
                  path('api/medicine/', medicineList, name='apiFlutterMedicine'),
                  path('api/storage', storageList, name='apiFlutterStorage'),
                  path('api/pharmacy/', pharmacyList, name='apiFlutterPharmacy'),
                  path('api/medicine/<str:pk>', medicineDetail, name='apiFlutterMed'),
                  
                  # Authentication
                  path('user/', UserRecordView.as_view(), name='users'),

                  # reset password
                  path('reset_password', auth_views.PasswordResetView.as_view(template_name="resetPassword.html"),
                       name='reset_password'),
                  path('reset_password_sent',
                       auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/',
                       auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
                       name='password_reset_confirm'),
                  path('reset_password_complete',
                       auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
                       name='password_reset_complete'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medicine/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
import os

# Create your models here.

# comment

accountType = [
    ('no', 'عادي'),
    ('ph', 'صيدلية'),
    ('or', 'مبادرة'),
]

requestType = [
    ('request', 'طلب'),
    ('donate', 'تبرع'),
]


def encodePath(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return os.path.join('license/', filename)


class user_info(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    accType = models.CharField(default='no', choices=accountType, max_length=3)

    def __str__(self):
        return self.username.username


class pharmacyAcc(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    pharmacyName = models.CharField(max_length=100)
    facebookPage = models.URLField(max_length=200, null=True, blank=True)
    phone_number = models.BigIntegerField()
    whatsappNumber = models.BigIntegerField(null=True, blank=True)
    licenseImg = models.ImageField(upload_to=encodePath)
    licenseNumber = models.CharField(max_length=30)


class CustomerAcc(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.BigIntegerField()


class organizationAcc(models.Model):
    username = models.OneToOneField(User, on_delete=models.CASCADE)
    organizationName = models.CharField(max_length=100)
    facebookPage = models.URLField(max_length=200, null=True, blank=True)
    phone_number = models.BigIntegerField()
    whatsappNumber = models.BigIntegerField(null=True, blank=True)



class medType(models.Model):
    typeEN = models.CharField(max_length=50)
    typeAR = models.CharField(max_length=50)

    def __str__(self):
        return self.typeAR


class medCategory(models.Model):
    categoryEN = models.CharField(max_length=50)
    categoryAR = models.CharField(max_length=50)

    def __str__(self):
        return self.categoryAR


class medicine(models.Model):
    generalName = models.CharField(max_length=100)
    arabicName = models.CharField(max_length=100, blank=True)
    scientificName = models.CharField(max_length=100)
    originCountry = models.CharField(max_length=100)
    type = models.ForeignKey(medType, on_delete=models.CASCADE,)
    category = models.ForeignKey(medCategory, on_delete=models.CASCADE,)
    manufactureCompanyAr = models.CharField(max_length=50, null=True, blank=True)
    manufactureCompanyEn = models.CharField(max_length=50)
    img = models.ImageField(upload_to="medicine/", default="profile.png")

    def __str__(self):
        return self.generalName


class storage(models.Model):
    medicine = models.ForeignKey(medicine, on_delete=models.CASCADE)
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.FloatField(null=True, blank=True)
    is_Available = models.BooleanField(default=True)
    updateDate = models.DateTimeField(auto_now=True)
    createDate = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "med : {} , pharmacy: {}".format(self.medicine.generalName, self.username)


class requestMedi(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    medicineGeneral = models.CharField(max_length=100)
    img = models.ImageField(upload_to="medicine/request/new/", default="profile.png", null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    requestDate = models.DateTimeField(auto_now_add=True)
    type = models.CharField(max_length=20, choices=requestType)
    prescription = models.ImageField(upload_to="medicine/request/", null=True, blank=True)

    def __str__(self):
        return "med : {} , user: {}".format(self.medicineGeneral, self.username)


class location(models.Model):
    username = models.ForeignKey(User, on_delete=models.CASCADE)
    location = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    locUrl = models.URLField(max_length=200)

medicine/templates/aboutus.html
{% extends 'index.html'%} {% load static %} {% block content %}

<section>
    <div class="container">
        <div class="col-md-12">
            <div class="p-5">
                <div class="profile col-md-12 text-right medicine-short-detail ml-auto mr-auto">

                    <div class="aboutus">
                        <div class="header mt-3 ">
                            <h4 style="color: #00000096;">من نحن</h4>
                        </div>
                        <div class="description mb-3">
                            <h6>اول موقع إلكتروني يهدف لخدمة مجال الدواء في السودان من خلال تقديم خدمة البحث عن الدواء أونلاين للمرضى و سهولة البحث عن الدواء ومعرفة المعلومات الخاصة به مثل المادة الفعالة لإيجاد البديل بسهولة في حال عدم توفر الدواء المطلوب</h6>
                        </div>

                        <div>
                            <h3>خدماتنا</h3>
                        </div>
                        
                        <div class="header">
                            <h5 style="color: #00000096;">طلب الدواء عبر الوصفة الطبية</h5>
                        </div>
                        <div class="description">
                            <h6>يوفر موقع دوائي طلب الدواء عبر صورة من الوصفة الطبية(الرورشتة) في حال عدم إيجاد الدواء المطلوب في قائمة الأدوية المتوفرة .</h6>
                        </div>

                        <div class="header mt-4">
                            <h5 style="color: #00000096;">معرفة مكان توفر الدواء</h5>
                        </div>
                        <div class="description">
                            <h6>يمكنك معرفة أماكن توفر الدواء المطلوب و التواصل مع الصيدلية الأقرب لك .</h6>
                        </div>

                        <div class="header mt-4">
                            <h5 style="color: #00000096;">مقارنة الأسعار بين مختلف الصيدليات</h5>
                        </div>
                        <div class="description">
                            <h6>يمكنك معرفة سعر الدواء في مختلف الصيدليات و إختيار الصيدلية التي تريد شراء الدواء منها .</h6>
                        </div>

                        <div class="header mt-4">
                            <h5 style="color: #00000096;">التبرع بالأدوية</h5>
                        </div>
                        <div class="description">
                            <h6>في حال كان لديك أدوية غير مستخدمة يمكنك التبرع بها عن طريق الموقع  .</h6>
                        </div>

                        <div class="mt-5">
                            <h3 class="mb-2">الشركاء</h3>
                            <img src="{% static 'medicine/img/sudanphcc.jpg'%} " alt="" class="" style="height: 150px;">

                        </div>

                    </div>
                    

                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

medicine/templates/adminDashboard.html
{% extends 'index.html'%}
{% block content %}

<section>
    <div class="container" style="background-color: white;">
        <div class="p-5">
            <div class="row pt-4" style="justify-content: space-between;">
                <div class="col-md-4 p-2">
                    <div class="p-3 Analytics">
                        <div class="Analyticshaeder">
                            <span>عدد الصيدليات المشاركة</span>
                        </div>
                        <div class="Analyticsnumbers">
                            <span>{{user_info}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 p-2">
                    <div class="p-3 Analytics">
                        <div class="Analyticshaeder">
                            <span>الأدوية الصورها موجودة</span>
                        </div>
                        <div class="Analyticsnumbers">
                            <span>{{medicinec}}</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 p-2">
                    <div class="p-3 Analytics">
                        <div class="Analyticshaeder">
                            <span>إجمالي الأدوية المضافة</span>
                        </div>
                        <div class="Analyticsnumbers">
                            <span>{{quantity}}</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="pt-4">
            <div class="listofstorage col-md-12 text-center medicine-short-detail ml-auto mr-auto">
                <h3 class="pt-3 pb-3">الأدوية اللي لازم نشتغلها + ما تشتغلو ب أول 195 دواء دواء</h3>
                <h4>الأدوية اللي تشتغلها براها بتطلع من القائمة هنا</h4>
                <div class="table-responsive">
                    <h4 class="bu"><a style="color: #000 !important" href="{% url 'addMedicine' %}">إضافة صنف دواء جديد</a></h4>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">إسم الدواء</th>
                                <th scope="col">الإسم العلمي</th>
                                <th scope="col">بلد التصنيع</th>                                
                                <th scope="col">تعديل</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for med in medicine %}
                            {% if med.img == 'profile.png' %}
                            <tr>
                                <th scope="row">{{ forloop.counter }}</th>
                                <td>{{med.generalName}}</td>
                                <td>{{med.scientificName}}</td>
                                <td>{{med.originCountry}}</td>
                                <td><a href="{% url 'edit_medicine' med.id %}">تعديل</a></td>
                            </tr>
                            {% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

medicine/templates/allMedicine.html
{% extends 'index.html'%} {% load static%} {% load humanize %} {% block content %}

<section>
    <div class="alert alert-warning" role="alert">
        يمكن ان تختلف الصورعن الدواء المعروض
    </div>
    <div class="container">

        <div class="p-3">
            <form class="form-inline d-flex justify-content-right md-form form-sm mt-0 mb-3" action="{% url 'search' %}" method="GET">
                <input class="form-control form-control-sm ml-1 w-50 search-bar" type="text" placeholder="أدخل إسم الدواء" aria-label="Search" name="search">
                <button class="btn btn-primary mt-3" style="height: 31px;" type="submit"><i class="fas fa-search"
                        aria-hidden="true"></i></button>
            </form>
            <div class="medicine-list">
                {% for storage in medicineList%}
                <div class="provider-medicine col-md-12">
                    <div class="m-2">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="image">
                                    <img src="{{storage.medicine.img.url}}" alt="لا تتوفر صورة للدواء" height="200" width="200">
                                </div>
                            </div>
                            <div class="col-md-9 text-right">
                                <h4>{{storage.medicine.generalName}}</h4>
                                <h5>{{storage.medicine.scientificName}}</h5>
                                {% if storage.username.user_info.accType == 'ph' %} {% if 'صيدلية' in storage.username.pharmacyacc.pharmacyName or 'صيدليه' in storage.username.pharmacyacc.pharmacyName %}
                                <h6><a href="{% url 'visitProfile' storage.username.id %}" style="color: #26317d">{{storage.username.pharmacyacc.pharmacyName}}</a>
                                </h6>
                                {% else %}
                                <h6><a href="{% url 'visitProfile' storage.username.id %}" style="color: #26317d">صيدلية
                                        {{storage.username.pharmacyacc.pharmacyName}}</a></h6>
                                {% endif%} {% elif storage.username.pharmacyAcc.accType == 'or' %}
                                <h6>
                                    <a href="{% url 'visitProfile' storage.username.id %}"><span
                                            style="color: #0f0f0fff;">مبادرة</span>
                                        {{storage.username.organizationacc.organizationName}}</a>
                                </h6>
                                {% else %}
                                <h6>
                                    <a href="{% url 'visitProfile' storage.username.id %}">{{storage.username.first_name|upper}}
                                        {{storage.username.last_name |upper}}</a>
                                </h6>
                                {% endif %}
                                <h6><span>أخر تحديث :</span> <span style="color:#0d0">
                                        {{storage.updateDate | naturalday}}</span></h6>
                                <h6><span>الموقع :</span><span> {% for loc in storage.username.location_set.all %}
                                    <i class="fas fa-map-marker-alt"></i>
                                        {{loc.city}},
                                        {{loc.location}} <br>{% endfor %}</span></h6> <a href="{% url 'productinfo' storage.id%}"><span class="btn btn-info"
                                        style="float:left;">تواصل مع الصيدلية</span></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

medicine/templates/allRequest.html
{% extends 'index.html'%} {% load static%} {% load humanize %} {% block content %}

<section>
    <div class="alert alert-warning" role="alert">
        يمكن ان تختلف الصورعن الدواء المعروض
    </div>
    <div class="container">

        <div class="p-3">
            <form class="form-inline d-flex justify-content-right md-form form-sm mt-0 mb-3" action="{% url 'searchRequest' %}" method="GET">
                <input class="form-control form-control-sm ml-1 w-50 search-bar" type="text" placeholder="أدخل إسم الدواء" aria-label="Search" name="search">
                <button class="btn btn-primary mt-2" style="height: 31px;" type="submit"><i class="fas fa-search"
                        aria-hidden="true"></i></button>
            </form>
            <div class="medicine-list">
                {% for request in medicineList%}
                <div class="provider-medicine col-md-12">
                    <div class="m-2">
                        <div class="row">
                            <div class="col-md-3">
                                <div class="image">
                                    <img src="{{request.img.url}}" alt="لا تتوفر صورة للدواء" height="200" width="200">
                                </div>
                            </div>
                            <div class="col-md-9 text-right">
                                <h4>{{request.medicineGeneral}}</h4>
                                <h6>
                                    <a href="{% url 'visitProfile' request.username.id %}"><span>{{request.username.first_name}}</span></a>
                                </h6>
                                <h6><span>تاريخ الطلب :</span> <br> <span style="color:#0d0">
                                        {{request.requestDate | naturalday}}</span></h6>
                                <h6><span>الموقع : </span> <br> {% for loc in request.username.location_set.all %} <i class="fas fa-map-marker-alt"></i> {{loc.city}}, {{loc.location}}
                                    <br>{% endfor %}</h6>
                                <a href="{% url 'requestinfo' request.id%}"><span class="btn btn-info"
                                        style="float:left;">تواصل</span></a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>

{% endblock %}

medicine/templates/contact.html
{% extends 'index.html'%}
{% block content %}

<section>
    <div class="container">
        <div class="col-md-12">
            <div class="p-5">
                <div class="profile col-md-12 text-right medicine-short-detail ml-auto mr-auto">
                    <h3 class="text-center mb-2">إتصل بنا</h3>
                    <form name="form" style="text-align: right;" method="POST" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{form}}
                        {{msg}}
                        <div class="checkbox mb-3">
                        </div>
                        <button class="btn btn-lg btn-primary btn-block col-md-12 col-11" type="submit">إرسال</button>

                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

medicine/templates/editMed.html
{% extends 'index.html'%}
{% block content %}

        <section>
            <div class="container">
                <div class="col-md-12">
                    <div class="p-5">
                        <div class="profile col-md-12 text-right medicine-short-detail ml-auto mr-auto">
                            <form style=" text-align: right;" method="post" action="">
                                {% csrf_token %}
                                {% for field in form %}
                                {{field.label}}
                                {{field}}
                                {% endfor %}
                                {{msg}}
                                <div class="checkbox mb-3">
                                </div>
                                <button class="btn btn-lg btn-primary btn-block" type="submit">تحديث</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

medicine/templates/edit_medicine.html
{% extends 'index.html'%}

{% block javaScriptHeader %}
<script>
    $(document).ready(function() {
        $('#id_medicine').select2();        
    })
</script>

{% endblock %}

{% block content %}

<section>
    <div class="container">
        <div class="col-md-12">
            <div class="p-5">
                <div class="profile col-md-12 text-center medicine-short-detail ml-auto mr-auto">
                    <form style=" text-align: right;" method="post" action="" enctype="multipart/form-data">
                        {% csrf_token %}
                        <h3 style=" text-align: center;"><span>تعديل معلومات الدواء</span></h3>
                        <h5>المهم يا جماعة اذا ما عرفتو تصنيف الدواء اكتبو أي شئ بنعدلها لقدام و ترجمو الأسماء للعربي و أهم شئ الصور باللّه اذا لقيت محل الصورة مكتوب profile معناتها لسه الصورة ما اتصلحت و اذا لقيت مكتوب اي إسم تاني معناتها في صورة و الدواء ما محتاج ل شئ </h5>
                        <h6><span>الإسم التجاري : </span><span style="font-size: 20px;">{{med.generalName}}</span></h6>
                        <h6><span>الإسم العلمي : </span> {{med.scientificName}} </h6>
                        <h6><span>إسم الشركة المصنعة : </span><span style="font-size: 20px;">{{med.manufactureCompanyEn}}</span></h6>
                        <h6><span>بلد التصنيع : </span><span style="font-size: 20px;">{{med.originCountry}}</span></h6>
                        <h6>{{med.originCountry}}</h6>
                        
                        {{form}}
                        {{msg}}
                        <div class="checkbox mb-3">
                        </div>
                        <button class="btn btn-lg btn-primary btn-block" type="submit">إضافة</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}



edit_medicine

medicine/templates/password_reset_done.html
{% extends 'index.html'%}
{% block content %}

<section>
    <div class="container">
        <div class="col-md-12">
            <div class="p-5">
                <div class="row">
                    <div class="profile col-md-12 text-center medicine-short-detail m-auto"
                        style="margin-bottom: 10px!important">
                        <h3>لقد تم إرسال رسالة إستعادة كلمة المرور</h3>
                        <h6>الرجاء التحقق من البريد الإلكتروني و إتباع التعليمات المذكورة لإستعادة كلمة المرور للحساب الخاص بك</h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

medicine/templates/sign.html
{% extends 'index.html'%}
{% block content %}

<section>
            <div class="container">
                <div class="col-md-12">
                    <div class="p-5">
                        <div class="row">
                            <div class="signin-signup col-md-5 text-right medicine-short-detail m-auto">
                                <div class="p-3">
                                    <form class="form-signin" action="" method="post">
                                        {% csrf_token %}
                                        <h1 class="h3 mb-3 font-weight-normal" style="margin-bottom: 20px !important;">
                                            تسجيل دخول</h1>
                                        {{form.username}}
                                        {{form.username.errors }}
                                        {{form.password}}
                                        {{form.password.errors }}
                                        {{msg1}}
                                        <p><a href="{% url 'reset_password' %}" style="color:#260ffd;">هل نسيت كلمة السر ؟ </a></p>
                                        <p>ليس لديك حساب : <a href="{% url 'signup' %}" style="color:#260ffd;">تسجيل حساب جديد</a></p>
                                        
                                        <div class="checkbox mb-3"></div>
                                        <button class="btn btn-lg btn-primary btn-block" type="submit">دخول</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}

medicine/templates/signup.html
{% extends 'index.html'%}
{% block content %}

<section>
            <div class="container">
                <div class="col-md-12">
                    <div class="p-5">
                        <div class="row">
                            <div class="signin-signup col-md-5 text-center m-auto">
                                <div class="p-3">
                                    <form class="form-signin" method="post" action="">
                                        {% csrf_token %}
                                        <h1 class="h3 mb-2 font-weight-normal" style="margin-bottom: 20px !important;">
                                            تسجيل حساب جديد</h1>
                                        {{form}}
                                        <div class="left">{{accTypeform}}</div>
                                        <div class="checkbox mb-3 text-right">
                                            <p> عند الضغط على زر التسجيل هذا يعني أنك موافق على <a href="{% url 'privacy' %}" style="color: #260ffd;">سياسات الخصوصية</a></p>
                                        </div>
                                        <button class="btn btn-lg btn-primary btn-block" type="submit">التسجيل</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock %}